Started logging messages at Wed Nov 06 11:34:01 2019
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 2 B-reps in file
Info:    Found 184 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 71
Info:            Created 
Info:        Working on 17
Info:            Created 
Info:        Working on 136
Info:            Created 
Info:        Working on 25
Info:            Created 
Info:        Working on 133
Info:            Created 
Info:        Working on 35
Info:            Created 
Info:        Working on 201
Info:            Created 
Info:        Working on 202
Info:            Created 
Info:        Working on 300
Info:            Created 
Info:        Working on 458
Info:            Created 
Info:        Working on 468
Info:            Created 
Info:        Working on 309
Info:            Created 
Info:        Working on 49
Info:            Created 
Info:        Working on 288
Info:            Created 
Info:        Working on 289
Info:            Created 
Info:        Working on 433
Info:            Created 
Info:        Working on 637
Info:            Created 
Info:        Working on 646
Info:            Created 
Info:        Working on 442
Info:            Created 
Info:        Working on 65
Info:            Created 
Info:        Working on 421
Info:            Created 
Info:        Working on 422
Info:            Created 
Info:        Working on 611
Info:            Created 
Info:        Working on 842
Info:            Created 
Info:        Working on 852
Info:            Created 
Info:        Working on 620
Info:            Created 
Info:        Working on 85
Info:            Created 
Info:        Working on 687
Info:            Created 
Info:        Working on 114
Info:            Created 
Info:        Working on 833
Info:            Created 
Info:        Working on 834
Info:            Created 
Info:        Working on 1102
Info:            Created 
Info:        Working on 1425
Info:            Created 
Info:        Working on 1433
Info:            Created 
Info:        Working on 1111
Info:            Created 
Info:        Working on 165
Info:            Created 
Info:        Working on 1091
Info:            Created 
Info:        Working on 1092
Info:            Created 
Info:        Working on 1401
Info:            Created 
Info:        Working on 1735
Info:            Created 
Info:        Working on 1744
Info:            Created 
Info:        Working on 1410
Info:            Created 
Info:        Working on 255
Info:            Created 
Info:        Working on 1389
Info:            Created 
Info:        Working on 1390
Info:            Created 
Info:        Working on 1710
Info:            Created 
Info:        Working on 1995
Info:            Created 
Info:        Working on 2005
Info:            Created 
Info:        Working on 1719
Info:            Created 
Info:        Working on 396
Info:            Created 
Info:        Working on 671
Info:            Created 
Info:        Working on 480
Info:            Created 
Info:        Working on 464
Info:            Created 
Info:        Working on 903
Info:            Created 
Info:        Working on 666
Info:            Created 
Info:        Working on 911
Info:            Created 
Info:        Working on 898
Info:            Created 
Info:        Working on 682
Info:            Created 
Info:        Working on 677
Info:            Created 
Info:        Working on 479
Info:            Created 
Info:        Working on 474
Info:            Created 
Info:        Working on 318
Info:            Created 
Info:        Working on 890
Info:            Created 
Info:        Working on 1169
Info:            Created 
Info:        Working on 482
Info:            Created 
Info:        Working on 657
Info:            Created 
Info:        Working on 652
Info:            Created 
Info:        Working on 658
Info:            Created 
Info:        Working on 450
Info:            Created 
Info:        Working on 881
Info:            Created 
Info:        Working on 643
Info:            Created 
Info:        Working on 1161
Info:            Created 
Info:        Working on 876
Info:            Created 
Info:        Working on 1156
Info:            Created 
Info:        Working on 1133
Info:            Created 
Info:        Working on 864
Info:            Created 
Info:        Working on 848
Info:            Created 
Info:        Working on 1456
Info:            Created 
Info:        Working on 1128
Info:            Created 
Info:        Working on 1464
Info:            Created 
Info:        Working on 1451
Info:            Created 
Info:        Working on 1144
Info:            Created 
Info:        Working on 1139
Info:            Created 
Info:        Working on 863
Info:            Created 
Info:        Working on 858
Info:            Created 
Info:        Working on 629
Info:            Created 
Info:        Working on 2086
Info:            Created 
Info:        Working on 868
Info:            Created 
Info:        Working on 1766
Info:            Created 
Info:        Working on 1445
Info:            Created 
Info:        Working on 1151
Info:            Created 
Info:        Working on 2050
Info:            Created 
Info:        Working on 1477
Info:            Created 
Info:        Working on 2057
Info:            Created 
Info:        Working on 1807
Info:            Created 
Info:        Working on 1777
Info:            Created 
Info:        Working on 1772
Info:            Created 
Info:        Working on 1444
Info:            Created 
Info:        Working on 1439
Info:            Created 
Info:        Working on 1120
Info:            Created 
Info:        Working on 2039
Info:            Created 
Info:        Working on 2268
Info:            Created 
Info:        Working on 1447
Info:            Created 
Info:        Working on 1755
Info:            Created 
Info:        Working on 1750
Info:            Created 
Info:        Working on 1756
Info:            Created 
Info:        Working on 1418
Info:            Created 
Info:        Working on 2030
Info:            Created 
Info:        Working on 1741
Info:            Created 
Info:        Working on 2260
Info:            Created 
Info:        Working on 2025
Info:            Created 
Info:        Working on 2255
Info:            Created 
Info:        Working on 2236
Info:            Created 
Info:        Working on 2017
Info:            Created 
Info:        Working on 2001
Info:            Created 
Info:        Working on 2434
Info:            Created 
Info:        Working on 2231
Info:            Created 
Info:        Working on 2442
Info:            Created 
Info:        Working on 2429
Info:            Created 
Info:        Working on 2247
Info:            Created 
Info:        Working on 2242
Info:            Created 
Info:        Working on 2016
Info:            Created 
Info:        Working on 2011
Info:            Created 
Info:        Working on 1727
Info:            Created 
Info:        Working on 1206
Info:            Created 
Info:        Working on 1513
Info:            Created 
Info:        Working on 1193
Info:            Created 
Info:        Working on 1828
Info:            Created 
Info:        Working on 1511
Info:            Created 
Info:        Working on 1830
Info:            Created 
Info:        Working on 1826
Info:            Created 
Info:        Working on 1521
Info:            Created 
Info:        Working on 1519
Info:            Created 
Info:        Working on 1205
Info:            Created 
Info:        Working on 1202
Info:            Created 
Info:        Working on 923
Info:            Created 
Info:        Working on 2092
Info:            Created 
Info:        Working on 1822
Info:            Created 
Info:        Working on 1208
Info:            Created 
Info:        Working on 1502
Info:            Created 
Info:        Working on 1500
Info:            Created 
Info:        Working on 1503
Info:            Created 
Info:        Working on 1180
Info:            Created 
Info:        Working on 1817
Info:            Created 
Info:        Working on 1492
Info:            Created 
Info:        Working on 2090
Info:            Created 
Info:        Working on 1815
Info:            Created 
Info:        Working on 2088
Info:            Created 
Info:        Working on 1801
Info:            Created 
Info:        Working on 2076
Info:            Created 
Info:        Working on 1792
Info:            Created 
Info:        Working on 2307
Info:            Created 
Info:        Working on 2075
Info:            Created 
Info:        Working on 2308
Info:            Created 
Info:        Working on 2306
Info:            Created 
Info:        Working on 2081
Info:            Created 
Info:        Working on 2080
Info:            Created 
Info:        Working on 1800
Info:            Created 
Info:        Working on 1799
Info:            Created 
Info:        Working on 1474
Info:            Created 
Info:        Working on 2750
Info:            Created 
Info:        Working on 1805
Info:            Created 
Info:        Working on 2302
Info:            Created 
Info:        Working on 2486
Info:            Created 
Info:        Working on 2084
Info:            Created 
Info:        Working on 2645
Info:            Created 
Info:        Working on 2311
Info:            Created 
Info:        Working on 2647
Info:            Created 
Info:        Working on 2497
Info:            Created 
Info:        Working on 2494
Info:            Created 
Info:        Working on 2492
Info:            Created 
Info:        Working on 2301
Info:            Created 
Info:        Working on 2298
Info:            Created 
Info:        Working on 2069
Info:            Created 
Info:        Working on 2748
Info:            Created 
Info:        Working on 2640
Info:            Created 
Info:        Working on 2304
Info:            Created 
Info:        Working on 2478
Info:            Created 
Info:        Working on 2475
Info:            Created 
Info:        Working on 2479
Info:            Created 
Info:        Working on 2279
Info:            Created 
Info:        Working on 2634
Info:            Created 
Info:        Working on 2467
Info:            Created 
Info:        Working on 2746
Info:            Created 
Info:        Working on 2632
Info:            Created 
Info:        Working on 2744
Info:            Created 
Info:        Working on 2620
Info:            Created 
Info:        Working on 2731
Info:            Created 
Info:        Working on 2608
Info:            Created 
Info:        Working on 2795
Info:            Created 
Info:        Working on 2729
Info:            Created 
Info:        Working on 2797
Info:            Created 
Info:        Working on 2793
Info:            Created 
Info:        Working on 2739
Info:            Created 
Info:        Working on 2737
Info:            Created 
Info:        Working on 2619
Info:            Created 
Info:        Working on 2617
Info:            Created 
Info:        Working on 2454
Info:            Created 
Info:        Working on 2799
Info:            Created 
Info:        Working on 2624
Info:            Created 
Info:        Working on 2753
Info:            Created 
Info:        Working on 2741
Info:            Created 
Info:        Working on 2656
Info:            Created 
Info:        Working on 2755
Info:            Created 
Info:        Working on 2508
Info:            Created 
Info:        Working on 2658
Info:            Created 
Info:        Working on 2322
Info:            Created 
Info:        Working on 2510
Info:            Created 
Info:        Working on 2105
Info:            Created 
Info:        Working on 2324
Info:            Created 
Info:        Working on 690
Info:            Created 
Info:        Working on 928
Info:            Created 
Info:        Working on 206
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 0.000106833
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 1
Info:        Working on 81
Info:            Created 
Info:        Working on 21
Info:            Created 
Info:        Working on 161
Info:            Created 
Info:        Working on 30
Info:            Created 
Info:        Working on 158
Info:            Created 
Info:        Working on 42
Info:            Created 
Info:        Working on 246
Info:            Created 
Info:        Working on 247
Info:            Created 
Info:        Working on 371
Info:            Created 
Info:        Working on 553
Info:            Created 
Info:        Working on 563
Info:            Created 
Info:        Working on 380
Info:            Created 
Info:        Working on 57
Info:            Created 
Info:        Working on 359
Info:            Created 
Info:        Working on 360
Info:            Created 
Info:        Working on 528
Info:            Created 
Info:        Working on 743
Info:            Created 
Info:        Working on 753
Info:            Created 
Info:        Working on 537
Info:            Created 
Info:        Working on 75
Info:            Created 
Info:        Working on 516
Info:            Created 
Info:        Working on 517
Info:            Created 
Info:        Working on 718
Info:            Created 
Info:        Working on 973
Info:            Created 
Info:        Working on 983
Info:            Created 
Info:        Working on 727
Info:            Created 
Info:        Working on 100
Info:            Created 
Info:        Working on 794
Info:            Created 
Info:        Working on 139
Info:            Created 
Info:        Working on 964
Info:            Created 
Info:        Working on 965
Info:            Created 
Info:        Working on 1258
Info:            Created 
Info:        Working on 1591
Info:            Created 
Info:        Working on 1600
Info:            Created 
Info:        Working on 1266
Info:            Created 
Info:        Working on 210
Info:            Created 
Info:        Working on 1246
Info:            Created 
Info:        Working on 1247
Info:            Created 
Info:        Working on 1566
Info:            Created 
Info:        Working on 1878
Info:            Created 
Info:        Working on 1888
Info:            Created 
Info:        Working on 1575
Info:            Created 
Info:        Working on 326
Info:            Created 
Info:        Working on 1554
Info:            Created 
Info:        Working on 1555
Info:            Created 
Info:        Working on 1854
Info:            Created 
Info:        Working on 2113
Info:            Created 
Info:        Working on 2123
Info:            Created 
Info:        Working on 1863
Info:            Created 
Info:        Working on 491
Info:            Created 
Info:        Working on 789
Info:            Created 
Info:        Working on 574
Info:            Created 
Info:        Working on 569
Info:            Created 
Info:        Working on 1042
Info:            Created 
Info:        Working on 784
Info:            Created 
Info:        Working on 1034
Info:            Created 
Info:        Working on 1029
Info:            Created 
Info:        Working on 778
Info:            Created 
Info:        Working on 773
Info:            Created 
Info:        Working on 575
Info:            Created 
Info:        Working on 559
Info:            Created 
Info:        Working on 389
Info:            Created 
Info:        Working on 1010
Info:            Created 
Info:        Working on 1316
Info:            Created 
Info:        Working on 577
Info:            Created 
Info:        Working on 765
Info:            Created 
Info:        Working on 749
Info:            Created 
Info:        Working on 764
Info:            Created 
Info:        Working on 545
Info:            Created 
Info:        Working on 1021
Info:            Created 
Info:        Working on 759
Info:            Created 
Info:        Working on 1324
Info:            Created 
Info:        Working on 1016
Info:            Created 
Info:        Working on 1311
Info:            Created 
Info:        Working on 1299
Info:            Created 
Info:        Working on 994
Info:            Created 
Info:        Working on 989
Info:            Created 
Info:        Working on 1629
Info:            Created 
Info:        Working on 1294
Info:            Created 
Info:        Working on 1621
Info:            Created 
Info:        Working on 1616
Info:            Created 
Info:        Working on 1288
Info:            Created 
Info:        Working on 1283
Info:            Created 
Info:        Working on 995
Info:            Created 
Info:        Working on 979
Info:            Created 
Info:        Working on 736
Info:            Created 
Info:        Working on 2204
Info:            Created 
Info:        Working on 999
Info:            Created 
Info:        Working on 1921
Info:            Created 
Info:        Working on 1609
Info:            Created 
Info:        Working on 1306
Info:            Created 
Info:        Working on 2176
Info:            Created 
Info:        Working on 1642
Info:            Created 
Info:        Working on 2168
Info:            Created 
Info:        Working on 1951
Info:            Created 
Info:        Working on 1912
Info:            Created 
Info:        Working on 1907
Info:            Created 
Info:        Working on 1610
Info:            Created 
Info:        Working on 1597
Info:            Created 
Info:        Working on 1275
Info:            Created 
Info:        Working on 2146
Info:            Created 
Info:        Working on 2361
Info:            Created 
Info:        Working on 1612
Info:            Created 
Info:        Working on 1900
Info:            Created 
Info:        Working on 1884
Info:            Created 
Info:        Working on 1899
Info:            Created 
Info:        Working on 1583
Info:            Created 
Info:        Working on 2157
Info:            Created 
Info:        Working on 1894
Info:            Created 
Info:        Working on 2369
Info:            Created 
Info:        Working on 2152
Info:            Created 
Info:        Working on 2356
Info:            Created 
Info:        Working on 2348
Info:            Created 
Info:        Working on 2134
Info:            Created 
Info:        Working on 2129
Info:            Created 
Info:        Working on 2527
Info:            Created 
Info:        Working on 2343
Info:            Created 
Info:        Working on 2519
Info:            Created 
Info:        Working on 2514
Info:            Created 
Info:        Working on 2337
Info:            Created 
Info:        Working on 2332
Info:            Created 
Info:        Working on 2135
Info:            Created 
Info:        Working on 2119
Info:            Created 
Info:        Working on 1871
Info:            Created 
Info:        Working on 1360
Info:            Created 
Info:        Working on 1686
Info:            Created 
Info:        Working on 1357
Info:            Created 
Info:        Working on 1974
Info:            Created 
Info:        Working on 1684
Info:            Created 
Info:        Working on 1972
Info:            Created 
Info:        Working on 1970
Info:            Created 
Info:        Working on 1678
Info:            Created 
Info:        Working on 1676
Info:            Created 
Info:        Working on 1361
Info:            Created 
Info:        Working on 1348
Info:            Created 
Info:        Working on 1054
Info:            Created 
Info:        Working on 2208
Info:            Created 
Info:        Working on 1959
Info:            Created 
Info:        Working on 1363
Info:            Created 
Info:        Working on 1668
Info:            Created 
Info:        Working on 1656
Info:            Created 
Info:        Working on 1667
Info:            Created 
Info:        Working on 1335
Info:            Created 
Info:        Working on 1966
Info:            Created 
Info:        Working on 1665
Info:            Created 
Info:        Working on 2210
Info:            Created 
Info:        Working on 1964
Info:            Created 
Info:        Working on 2206
Info:            Created 
Info:        Working on 1944
Info:            Created 
Info:        Working on 2199
Info:            Created 
Info:        Working on 1943
Info:            Created 
Info:        Working on 2409
Info:            Created 
Info:        Working on 2198
Info:            Created 
Info:        Working on 2408
Info:            Created 
Info:        Working on 2407
Info:            Created 
Info:        Working on 2194
Info:            Created 
Info:        Working on 2193
Info:            Created 
Info:        Working on 1945
Info:            Created 
Info:        Working on 1936
Info:            Created 
Info:        Working on 1639
Info:            Created 
Info:        Working on 2784
Info:            Created 
Info:        Working on 1949
Info:            Created 
Info:        Working on 2402
Info:            Created 
Info:        Working on 2579
Info:            Created 
Info:        Working on 2202
Info:            Created 
Info:        Working on 2710
Info:            Created 
Info:        Working on 2412
Info:            Created 
Info:        Working on 2708
Info:            Created 
Info:        Working on 2582
Info:            Created 
Info:        Working on 2573
Info:            Created 
Info:        Working on 2571
Info:            Created 
Info:        Working on 2403
Info:            Created 
Info:        Working on 2393
Info:            Created 
Info:        Working on 2187
Info:            Created 
Info:        Working on 2780
Info:            Created 
Info:        Working on 2695
Info:            Created 
Info:        Working on 2405
Info:            Created 
Info:        Working on 2564
Info:            Created 
Info:        Working on 2551
Info:            Created 
Info:        Working on 2563
Info:            Created 
Info:        Working on 2380
Info:            Created 
Info:        Working on 2703
Info:            Created 
Info:        Working on 2560
Info:            Created 
Info:        Working on 2782
Info:            Created 
Info:        Working on 2701
Info:            Created 
Info:        Working on 2778
Info:            Created 
Info:        Working on 2682
Info:            Created 
Info:        Working on 2773
Info:            Created 
Info:        Working on 2680
Info:            Created 
Info:        Working on 2807
Info:            Created 
Info:        Working on 2771
Info:            Created 
Info:        Working on 2805
Info:            Created 
Info:        Working on 2803
Info:            Created 
Info:        Working on 2765
Info:            Created 
Info:        Working on 2763
Info:            Created 
Info:        Working on 2683
Info:            Created 
Info:        Working on 2671
Info:            Created 
Info:        Working on 2539
Info:            Created 
Info:        Working on 2809
Info:            Created 
Info:        Working on 2687
Info:            Created 
Info:        Working on 2787
Info:            Created 
Info:        Working on 2775
Info:            Created 
Info:        Working on 2719
Info:            Created 
Info:        Working on 2789
Info:            Created 
Info:        Working on 2593
Info:            Created 
Info:        Working on 2721
Info:            Created 
Info:        Working on 2423
Info:            Created 
Info:        Working on 2595
Info:            Created 
Info:        Working on 2223
Info:            Created 
Info:        Working on 2425
Info:            Created 
Info:        Working on 797
Info:            Created 
Info:        Working on 1059
Info:            Created 
Info:        Working on 251
Info:            Created 
Info:        Created 
Info:    Working on BRep 1
Info:        Using 3D tolerance 0.000106833
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  2 found       2 created       0 failed
Finished logging messages at Wed Nov 06 11:34:02 2019
